# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('c_image', models.FileField(upload_to='')),
                ('party_affiliate', models.CharField(choices=[('Democratic', 'Democratic'), ('Republican', 'Republican'), ('Third Party', 'Third Party')], max_length=11)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='candidates',
            unique_together=set([('first_name', 'middle_name', 'last_name', 'dob')]),
        ),
    ]
