# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegistration',
            new_name='UserLogin',
        ),
    ]
