# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20161104_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='first_name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='userlogin',
            old_name='last_name',
            new_name='user_name',
        ),
    ]
