# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20161104_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='user_name',
            new_name='username',
        ),
    ]
