# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20161104_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
